export declare const IPC_EVENT_NAMES: {
    FILE_OPENED: string;
    URL_OPENED: string;
    CERTIFICATE_ERROR: string;
    IMPORT_APP_DATA: string;
    EXPORT_APP_DATA: string;
    CREATE_TAB: string;
    CLOSE_TAB: string;
    NEXT_TAB: string;
    PREVIOUS_TAB: string;
    REOPEN_CLOSED_TAB: string;
    SEND_REQUEST: string;
    RELOAD_DOCS: string;
    SHOW_DOCS: string;
    SHOW_SETTINGS: string;
    GET_FILE_OPENED: string;
    UPDATE_AVAILABLE: string;
    RENDERER_READY: string;
    RENDERER_UPDATE_APP: string;
    RENDERER_RESTART_APP: string;
    RENDERER_GET_AUTOBACKUP_DATA: string;
    RENDERER_SAVE_AUTOBACKUP_DATA: string;
    RENDERER_GET_AUTH_TOKEN: string;
    RENDERER_SET_INTEROP_APP_STATE: string;
    RENDERER_SET_INTEROP_WINDOW_STATE: string;
    RENDERER_SET_INTEROP_ACTIVE_WINDOW_ID_STATE: string;
    RENDERER_REMOVE_INTEROP_WINDOW_STATE: string;
};
export declare const STORE_EVENTS: {
    LENGTH: string;
    CLEAR: string;
    GET_ITEM: string;
    KEY_BY_INDEX: string;
    REMOVE_ITEM: string;
    SET_ITEM: string;
    GET_STORE_OBJECT: string;
};
export declare const ALTAIR_CUSTOM_PROTOCOL = "altair";
export declare const electronApiKey = "electronApi";
export declare const ALTAIR_WINDOW_ID_HEADER = "x-altair-window-id";
export declare const ELECTRON_ALLOWED_FORBIDDEN_HEADERS: string[];
//# sourceMappingURL=constants.d.ts.map