// Generated by dts-bundle-generator v6.12.0

/**
 * Returns the path to Altair assets, for resolving the assets when rendering Altair
 */
export declare const getDistDirectory: () => string;

export {};
