import { RequestHandlerIds } from '../request/types';
import { IDictionary } from '../types/shared';
import { IInitialEnvironments } from '../types/state/environments.interfaces';
import { HttpVerb } from '../types/state/query.interfaces';
import { ConfigEnvironment } from './environment';
import { AltairConfigOptions, AltairWindowOptions } from './options';
import { UrlConfig } from './urls';
export declare class AltairConfig {
    private localSandboxUrl;
    private useLocalSandboxUrl;
    donation: {
        url: string;
        action_count_threshold: number;
    };
    ga: string;
    add_query_depth_limit: number;
    tab_size: number;
    max_windows: number;
    default_language: string;
    languages: {
        'en-US': string;
        'fr-FR': string;
        'es-ES': string;
        'cs-CZ': string;
        'de-DE': string;
        'pt-BR': string;
        'ru-RU': string;
        'uk-UA': string;
        'zh-CN': string;
        'ja-JP': string;
        'sr-SP': string;
        'it-IT': string;
        'pl-PL': string;
        'ko-KR': string;
        'ro-RO': string;
        'vi-VN': string;
    };
    query_history_depth: number;
    disableLineNumbers: boolean;
    defaultTheme: string;
    themes: string[];
    isTranslateMode: any;
    isWebApp: any;
    cspNonce: string;
    initialData: {
        url: string;
        subscriptionsEndpoint: string;
        subscriptionsProtocol: string;
        query: string;
        variables: string;
        headers: IDictionary;
        environments: IInitialEnvironments;
        preRequestScript: string;
        postRequestScript: string;
        instanceStorageNamespace: string;
        settings: AltairConfigOptions["initialSettings"];
        persistedSettings: AltairConfigOptions["persistedSettings"];
        initialSubscriptionRequestHandlerId: AltairConfigOptions["initialSubscriptionRequestHandlerId"];
        initialSubscriptionsPayload: IDictionary;
        initialRequestHandlerId: RequestHandlerIds;
        initialRequestHandlerAdditionalParams: Record<string, unknown>;
        initialHttpMethod: HttpVerb;
        preserveState: boolean;
        windows: AltairWindowOptions[];
        disableAccount: boolean;
        initialAuthorization: AltairConfigOptions["initialAuthorization"];
    };
    constructor({ endpointURL, subscriptionsEndpoint, subscriptionsProtocol, initialQuery, initialHeaders, initialEnvironments, initialVariables, initialPreRequestScript, initialPostRequestScript, instanceStorageNamespace, initialSettings, persistedSettings, initialRequestHandlerId, initialRequestHandlerAdditionalParams, initialSubscriptionRequestHandlerId, initialSubscriptionsPayload, initialHttpMethod, preserveState, initialWindows, disableAccount, initialAuthorization, cspNonce, }?: AltairConfigOptions);
    private getPossibleLocalSandBoxRoot;
    private getLocalSandBoxUrl;
    getUrlConfig(environment?: ConfigEnvironment): UrlConfig;
    getUrlConfigWithLocal(environment?: ConfigEnvironment): Promise<UrlConfig>;
    getUrl(name: keyof UrlConfig, environment?: ConfigEnvironment): Promise<string>;
}
export declare const setAltairConfig: (_config: AltairConfig) => void;
export declare const getAltairConfig: () => AltairConfig;
//# sourceMappingURL=index.d.ts.map